In [62]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [30]:
auto = pd.read_csv("data/Auto.data")

In [57]:
x_train = auto[['displacement']]
y_train = auto['mpg']

In [58]:
#Same data is being fixed
lin_model1 = LinearRegression()
lin_model1.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [69]:
print ("Coefficient :{}".format(lin_model1.coef_))
print ("Intercept :{}".format(lin_model1.intercept_))
print ("R2:{}".format(r2_score(y_train,lin_model1.predict(x_train))))
print ("Adjusted R2:{}".format((1-(1-r2_score(y_train, lin_model1.predict(x_train)))*((len(y_train)-1)/(len(y_train)-1-1)))))

Coefficient :[-0.06005143]
Intercept :35.12063593840391
R2:0.6482294003193044
Adjusted R2:0.6473274244226872


In [70]:
x_train = x_train.append(x_train)
y_train = y_train.append(y_train)

In [71]:
#Same data is being fixed
lin_model1 = LinearRegression()
lin_model1.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [72]:
print ("Coefficient :{}".format(lin_model1.coef_))
print ("Intercept :{}".format(lin_model1.intercept_))
print ("R2:{}".format(r2_score(y_train,lin_model1.predict(x_train))))
print ("Adjusted R2:{}".format((1-(1-r2_score(y_train, lin_model1.predict(x_train)))*((len(y_train)-1)/(len(y_train)-1-1)))))

Coefficient :[-0.06005143]
Intercept :35.12063593840391
R2:0.6482294003193044
Adjusted R2:0.6477795657928586


In [99]:
x_train = x_train.append(auto[['displacement']])
y_train = auto['mpg']

lin_model1 = LinearRegression()
lin_model1.fit(x_train,y_train)

#Coefficient / Slope
np.round(lin_model1.coef_[0],2)

ValueError: Found input variables with inconsistent numbers of samples: [1176, 392]

In [36]:
x_train = auto[['cylinders','displacement','horsepower','weight','acceleration','year','origin']]
y_train = auto['mpg']

lin_model2 = LinearRegression()
lin_model2.fit(x_train,y_train)

#Coefficient / Slope
np.round(lin_model2.coef_[1],2)

0.02

In [27]:
lin_model.intercept_

35.12063593840391

In [117]:
X_train['GPA_IQ'] = X_train['GPA']*X_train['IQ']

In [119]:
X_train = pd.DataFrame({'GPA':[2,3,4,2,5,6,3,4,9,2,4,3,2,4,2,1,2,3,3,4],
                        'IQ':[100,92,26,37,87,98,76,45,88,99,37,58,25,98,46,26,87,98,36,56],
                        'Gender':[1,0,0,1,0,0,0,1,1,1,0,1,1,1,0,0,1,1,1,0]})
X_train['GPA_IQ'] = X_train['GPA']*X_train['IQ']
X_train['GPA_Gender'] = X_train['GPA']*X_train['Gender']

y_train = [37372,69824,361698,59673,52252,48959,1234,43828,37472,98985,3736,65527,98736,36462,367272,362562,74622,27362,37269,837282]


In [120]:
lin_mod = LinearRegression()
lin_mod.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [121]:
lin_mod.coef_

array([ 8.02126323e+03, -3.97652099e+01, -2.89605033e+05, -5.29394484e+02,
        3.56305076e+04])

In [122]:
lin_mod.intercept_

332512.95013699046

In [123]:
X_train = pd.DataFrame({'GPA':[2,3,4,2,5,6,3,4,9,2,4,3,2,4,2,1,2,3,3,4],
                        'IQ':[100,92,26,37,87,98,76,45,88,99,37,58,25,98,46,26,87,98,36,56],
                        'Gender':[0,1,1,0,1,1,1,0,0,0,1,0,0,0,1,1,0,0,0,1]})
X_train['GPA_IQ'] = X_train['GPA']*X_train['IQ']
X_train['GPA_Gender'] = X_train['GPA']*X_train['Gender']

y_train = [37372,69824,361698,59673,52252,48959,1234,43828,37472,98985,3736,65527,98736,36462,367272,362562,74622,27362,37269,837282]


In [124]:
lin_mod = LinearRegression()
lin_mod.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [125]:
lin_mod.coef_

array([ 4.36517708e+04, -3.97652099e+01,  2.89605033e+05, -5.29394484e+02,
       -3.56305076e+04])

In [194]:
4.36517708e+04/8.02126323e+03

5.4420070191363115

In [126]:
lin_mod.intercept_

42907.916935160145

In [128]:
332512.95013699046/42907.916935160145

7.749454503686673

In [184]:

train = pd.read_csv("data/train_ini.csv")
X_train = train.copy()

#----------------------------------------------------------
# Feature Engineering
#----------------------------------------------------------
#One Hot Encoding
X_train['IsHoliday_oh'] = X_train['IsHoliday'].astype(int)
#Extract Year, Month, Week, Date (Train)
X_train['day'] = pd.to_datetime(X_train['Date']).dt.day
X_train['week'] = pd.to_datetime(X_train['Date']).dt.week
X_train['month'] = pd.to_datetime(X_train['Date']).dt.month
X_train['year'] = pd.to_datetime(X_train['Date']).dt.year
X_train['IsHoliday_oh_day'] = X_train['IsHoliday_oh']*X_train['day']


y_train = train['Weekly_Sales']
X_train = X_train.drop(['IsHoliday','Date','Weekly_Sales'],axis=1)


In [185]:
lin_mod = LinearRegression()
lin_mod.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [186]:
lin_mod.coef_

array([-1.56256286e+02,  1.07499913e+02,  5.57940163e+02, -2.31768631e+02,
        1.53886415e+03, -6.49728005e+03, -7.58881798e+02, -2.10379953e+00])

In [187]:
lin_mod.intercept_

1546235.9370307403

In [188]:

train = pd.read_csv("data/train_ini.csv")
X_train = train.copy()

#----------------------------------------------------------
# Feature Engineering
#----------------------------------------------------------
#One Hot Encoding
X_train['IsHoliday_oh'] = (~(X_train['IsHoliday'])).astype(int)
#Extract Year, Month, Week, Date (Train)
X_train['day'] = pd.to_datetime(X_train['Date']).dt.day
X_train['week'] = pd.to_datetime(X_train['Date']).dt.week
X_train['month'] = pd.to_datetime(X_train['Date']).dt.month
X_train['year'] = pd.to_datetime(X_train['Date']).dt.year
X_train['IsHoliday_oh_day'] = X_train['IsHoliday_oh']*X_train['day']

y_train = train['Weekly_Sales']
X_train = X_train.drop(['IsHoliday','Date','Weekly_Sales'],axis=1)


In [189]:
lin_mod = LinearRegression()
lin_mod.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [192]:
lin_mod.

<bound method BaseEstimator.get_params of LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)>

In [190]:
lin_mod.coef_

array([-1.56256286e+02,  1.07499913e+02, -5.57940163e+02, -2.33872431e+02,
        1.53886415e+03, -6.49728005e+03, -7.58881798e+02,  2.10379953e+00])

In [191]:
lin_mod.intercept_

1546793.8771936428

In [193]:
X_train

Store  Dept  IsHoliday_oh  day  week  month  year  IsHoliday_oh_day
0           1     1             1    5     5      2  2010                 5
1           1     1             0   12     6      2  2010                 0
2           1     1             1   19     7      2  2010                19
3           1     1             1   26     8      2  2010                26
4           1     1             1    5     9      3  2010                 5
...       ...   ...           ...  ...   ...    ...   ...               ...
164110     45    98             1   28     4      1  2011                28
164111     45    98             1    4     5      2  2011                 4
164112     45    98             0   11     6      2  2011                 0
164113     45    98             1   18     7      2  2011                18
164114     45    98             1   25     8      2  2011                25

[164115 rows x 8 columns]