In [1]:
import numpy as np
import pandas as pd

In [45]:
df_iris = pd.read_csv('data/iris.csv')
df_dataI = pd.read_csv('data/dataI.csv')
iris = np.array(df_iris).T
datasetI = np.array(df_dataI).T

In [46]:
iris_mean=np.mean(iris,axis=1).reshape(iris.shape[0],1)
dataI_mean=np.mean(dataI,axis=1).reshape(dataI.shape[0],1)

In [47]:
irisA = iris-iris_mean
dataI = datasetI-dataI_mean

In [51]:
iris_eigenval,iris_eigenvec=np.linalg.eig(iris_cov)

In [70]:
eigenvec=iris_eigenvec[:,0].reshape(4,1)

In [74]:
eigenvec.shape[1]

1

In [77]:
eigenvec[:,0].reshape(eigenvec[:,0].shape[0],1)

(4, 1)

In [79]:
dataI.shape

(4, 150)

In [80]:
loop_eigenvec

NameError: name 'loop_eigenvec' is not defined

In [82]:
loop_eigenvec = eigenvec[:,e].reshape(eigenvec[:,e].shape[0],1)

In [93]:
np.dot(dataI.T,loop_eigenvec).shape

(150, 1)

In [111]:
np.dot(eigenvec[:,e].reshape(eigenvec[:,e].shape[0],1).T,dataI[:,3].reshape(4,1))

array([[-2.15680134]])

In [106]:
eigenvec[:,e].reshape(eigenvec[:,e].shape[0],1).T

array([[ 0.36138659, -0.08452251,  0.85667061,  0.3582892 ]])

In [108]:
dataI[:,0].reshape(4,1)

array([[-0.65153411],
       [-0.1378118 ],
       [-3.24506416],
       [-0.70685032]])

In [117]:
W=np.dot(loop_eigenvec.T,dataI)

In [125]:
(W*loop_eigenvec)

(4, 150)

In [127]:
new_dataset=dataI_mean+(np.dot(loop_eigenvec.T,dataI)*loop_eigenvec)

In [133]:
(np.sum((new_dataset-irisA)**2))/150

59.7400753020177

In [71]:
data_hat = np.zeros((data.shape[0],data.shape[1]))
for e in range(eigenvec.shape[1]):
    loop_eigenvec = eigenvec[:,e].reshape(eigenvec[:,e].shape[0],1)
    val = np.dot(loop_eigenvec.T,data)*loop_eigenvec
    data_hat += val

0


In [55]:
iris_eigenvec

array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
       [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
       [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
       [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]])

In [ ]:
data,data_mean,eigenvec
data_hat = np.zeros((data.shape[0],data.shape[1]))
for e in range(eigenvec.shape[1]):
    #print (eigenvec[:,e].reshape(eigenvec[:,e].shape[0],1))
    loop_eigenvec = eigenvec[:,e].reshape(eigenvec[:,e].shape[0],1)
    val = np.dot(loop_eigenvec.T,data)*loop_eigenvec
    data_hat += val
    #print ("Val:{}".format(val.shape))
    #print ("X_HAT:{}".format(data.shape))
data_hat += data_mean

