In [34]:
from sklearn.model_selection import KFold
from sklearn.datasets import load_boston
import numpy as np

In [284]:
boston_data = load_boston()
X = boston_data.data[:100,:]
y = boston_data.target

In [285]:
cv = KFold(n_splits=10)

In [376]:
data = np.random.normal(size=(100,2),loc=(0,1))

In [377]:
data.shape

(100, 2)

array([0.00e+000, 4.94e-324, 9.88e-324, 1.48e-323, 1.98e-323, 2.47e-323,
       2.96e-323, 3.46e-323, 3.95e-323, 4.45e-323, 4.94e-323, 5.43e-323,
       5.93e-323, 6.42e-323, 6.92e-323, 7.41e-323, 7.91e-323, 8.40e-323,
       8.89e-323, 9.39e-323, 9.88e-323, 1.04e-322, 1.09e-322, 1.14e-322,
       1.19e-322, 1.24e-322, 1.28e-322, 1.33e-322, 1.38e-322, 1.43e-322,
       1.48e-322, 1.53e-322, 1.58e-322, 1.63e-322, 1.68e-322, 1.73e-322,
       1.78e-322, 1.83e-322, 1.88e-322, 1.93e-322, 1.98e-322, 2.03e-322,
       2.08e-322, 2.12e-322, 2.17e-322, 2.22e-322, 2.27e-322, 2.32e-322,
       2.37e-322, 2.42e-322, 2.47e-322, 2.52e-322, 2.57e-322, 2.62e-322,
       2.67e-322, 2.72e-322, 2.77e-322, 2.82e-322, 2.87e-322, 2.91e-322,
       2.96e-322, 3.01e-322, 3.06e-322, 3.11e-322, 3.16e-322, 3.21e-322,
       3.26e-322, 3.31e-322, 3.36e-322, 3.41e-322, 3.46e-322, 3.51e-322,
       3.56e-322, 3.61e-322, 3.66e-322, 3.71e-322, 3.75e-322, 3.80e-322,
       3.85e-322, 3.90e-322, 3.95e-322, 4.00e-322, 

In [416]:
trn_idx = np.empty(shape=[1,0],dtype=int)
trn_idx

array([], shape=(1, 0), dtype=int64)

In [448]:
cross_validation()

Test Idx: [0 1 2 3 4 5 6 7 8 9]
Train Idx : [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Test Idx: [10 11 12 13 14 15 16 17 18 19]
Train Idx : [ 0  1  2  3  4  5  6  7  8  9 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Test Idx: [20 21 22 23 24 25 26 27 28 29]
Train Idx : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Test Idx: [30 31 32 33 

In [449]:
cv_array = np.empty([1,2],dtype=int)

In [450]:
cv_array

array([[0, 1]])

In [451]:
test_idx

array([95, 96, 97, 98, 99])

In [452]:
trn_idx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94])

In [492]:
cv_train  = [[]]

In [490]:
cv_train[0].append(trn_idx)
cv_train[1].append(test_idx)

IndexError: list index out of range

In [488]:
cv_train

[[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
         34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
         51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
         68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
         85, 86, 87, 88, 89, 90, 91, 92, 93, 94])]]

In [501]:
def cross_validation(n_splits=10,data_size=100):
    cv_train = []
    cv_test = []

    for c in np.arange(n_splits):
        trn_idx = np.empty(shape=[1,0],dtype=int)
        test_idx = np.arange((0+int(data_size/n_splits))*c,int(data_size/n_splits)*(c+1))
        cv_test.append(test_idx)
        for idx,val in enumerate(data):
            if idx not in test_idx:
                trn_idx = np.append(trn_idx,idx)
        trn_idx.sort()
        cv_train.append(trn_idx)
    return cv_train,cv_test

In [507]:
len(cv_train)

10

In [504]:
cv_train, cv_test = cross_validation(n_splits=10,data_size=100)

In [499]:
data[cv_test[0]]

array([[ 1.73633962,  1.54833269],
       [-0.60729533,  1.07365652],
       [-1.02549827,  1.31907971],
       [ 0.30552676,  0.38890816],
       [-1.2166387 ,  0.42058562]])

In [447]:
def cross_validation(n_splits=10,data_size=100):
    for c in np.arange(n_splits):
        trn_idx = np.empty(shape=[1,0],dtype=int)
        test_idx = np.arange((0+int(data_size/n_splits))*c,int(data_size/n_splits)*(c+1))
        print ("Test Idx: {}".format(test_idx))
        for idx,val in enumerate(data):
            if idx not in test_idx:
                trn_idx = np.append(trn_idx,idx)
        trn_idx.sort()
        print ("Train Idx : {}".format(trn_idx))

In [443]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits=20)
for train,test in kfold.split(data):
    print ("Test Index: {}".format(test))
    print ("Train Index: {}".format(train))

Test Index: [0 1 2 3 4]
Train Index: [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76
 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Test Index: [5 6 7 8 9]
Train Index: [ 0  1  2  3  4 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76
 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Test Index: [10 11 12 13 14]
Train Index: [ 0  1  2  3  4  5  6  7  8  9 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76
 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Test Index: [1

In [430]:
def cross_validation(n_splits=10):
        n_splits=20
        for c in np.arange(n_splits):
            trn_idx = np.empty(shape=[1,0],dtype=int)
            test_idx = np.arange((0+n_splits)*c,n_splits*(c+1))
            print ("Test Idx: {}".format(test_idx))
            for idx,val in enumerate(data):
                if idx not in test_idx:
                    trn_idx = np.append(trn_idx,idx)
            trn_idx.sort()
            print ("Train Idx : {}".format(trn_idx))

In [286]:
for train_index,test_index in cv.split(X):
    print ("Train Index : {}" .format(train_index))
    print ("Test Index: {}".format(test_index))

Train Index : [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Test Index: [0 1 2 3 4 5 6 7 8 9]
Train Index : [ 0  1  2  3  4  5  6  7  8  9 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Test Index: [10 11 12 13 14 15 16 17 18 19]
Train Index : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Test Index: [20 21 22 23 24 25 26 27 28 29]
Train Index

In [544]:
a = [5,6,3,4,9,10,1,37,482,1,4,8]
a_a = np.array(a)

In [537]:
np.argmin(a)

6

In [540]:
np.where(a==1)

(array([], dtype=int64),)

In [546]:
np.unravel_index(a_a.argmin(), a_a.shape)

(6,)

In [542]:
np.where(a == np.argmin(a))

(array([1]),)

In [530]:
np.isin(6,a)

array(True)

In [1]:
import numpy as np

In [5]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a = np.array([1,2,3,4,5,1,2,3,4,5])

In [35]:
np.max(np.where(a == np.min(a)))

5

In [29]:
np.max(np.where(a == np.argmin(a)))

ValueError: zero-size array to reduction operation maximum which has no identity

In [18]:
np.any(a< 5)

True

In [527]:
a[a == 6]

5

In [534]:
a.argmin(axis=0)

AttributeError: 'list' object has no attribute 'argmin'

In [531]:
np.argmin(a,axis=0)

6

In [508]:
data = [1,2,3,4,5,6,7,8,9,10]

In [513]:
mu = np.mean(data)

In [521]:
np.std(data)

2.8722813232690143

In [522]:
np.sqrt(np.sum((data - mu)**2)/10)

2.8722813232690143